server:
  port: 8080

# K8S API Server地址
kubernetes:
  url: https://192.168.137.200:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik84Y3JlX3VDNlN3N0NYMlFZeGxmYjRPZGlCRFFKXzhuUFdnYml3bDNSSkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFkbWluLXNlcnZpY2VhY2NvdW50LXRva2VuMSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbi1zZXJ2aWNlYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjFiYzAwNzUwLTM5N2YtNDI0My04ZTQzLTQ4M2M2M2UyOTc1YiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmFkbWluLXNlcnZpY2VhY2NvdW50In0.0LN6wM6SvEkG5oIjT9W5AFJmK4KAbOJbEWHeE0QfGIo4sdcByvzT6mGMcfBlDEsmVkTWtbrz4XdyjmYbmQ-DWhzbLWKU8BmRP34f9YHqflx-OAVGXiUZXSeZ8c0JPJgO6jc4mDqxFHt0-D12BH0X8pI-url4zDzau3hN2PR7dHhxSiYW85ABw60HRDp2qIJWwZoABBwHEQkZQ0pnVfpEu39BoVmQzMVn0Gp_cJ1f98gdjjJ57hFkPklJWgnLWVJUJha2pMTpgCLPShw5BDbjVkJkE8Tpf21wo_LfppO_rOG4kx4HFSBbI_vsAfatzce5-logCkzdGPppryQ3j8bQrw

spring:
  redis:
    host: localhost
    #    host: redis
    port: 6379
    password: ustb
    database: 3
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /


kubeshark:
  ws-url: ws://192.168.137.200:8899/api/wsFull
