apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kube-guard-webhook
webhooks:
  - name: guard.kube.com
    clientConfig:
      url: "https://192.168.137.200:9443/validate"
      caBundle:
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJT01XVTd1MTV3em93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBM01ERXhNVFF5TlRsYUZ3MHlOVEEzTURFeE1UUTRNREphTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQThEQzI3NE1yNGgwbGswZ3UKN1BJS0pBWDdQVGhScjdJcXRJNHlTWGQrT25MZlcyUkZhSisyWlRNc3NXUkZ4NlhjQVRPWGNPK21LOE1CNVcvegpwSVM0R2d0WjhpVWJyUkRNQzk4YjZIdGd3eVloaGVkbk5JRXdyQXI2NTlCdGU2QzJid3VjcHlHeFEvcEs0NklKClRJVkYwSGczNnlKdUU2MTlHKzNMTDBsQVFNVkNLdFNWcmN4NjhpZlRRS0N2aHpjMHdUZGdLSzR2VkpRK0Nyc1cKN2RJdTNBMUZkZGFVNTV5WTVCUW5VNXlhNXFPMVF2S3hrMGp3eGJkQjllL2ttZmtlQnpxckJ2ZXhBTW9GL01BbgorZVdmTEJuTXJJdG4ycjVCZVFMdzZnWGFqVkd6eXpuSnQvck5JUzFta2U3TzBlblBRZ29ITUk2MWdFK0oxbWtpCkRtdzhJd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSSS9QODQ1QmdWV0RnMUJaNFFCTldGZTVHMgpRekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBWG5YU1Z5a1gwc2YreWxjOGdnbjFMYjhCUUVnejIydlZiUGZvCjEvSlV5bDAwb01UN3VGZmttY1lKcG81Wmp1bXVhckNGUlZhYkhkVWp4dlJnRkpVMlZoVXJtU3F4UzcwSUVoT1cKSmFNYkV3bXhoRXFtdUN2THhGc0NxQVZJS2tNUDdGRnlLNkFISGZHTXdWU3BrSkk1NWJaTVFZZUdDMkZqcEN6RApQQmtvNFZxRlBaQTF4c1JPeHBPc05xeVpnZ0NycUlNelROWE5pdDRBTlV1TGNGWUI5Q0dkMGpUY1FhMXhGUVY5CkMyM3NJOG9GMVhXL2M5dTRtZ3M1dGtHV2FYQWVGMXd3V1BmektUeHpvSHVTcUpENk91VzlHZzVvVzdzbXo0QzcKWEkvclNzUW5uQ3R3S0k3UkNGS0hDL1BGRDBDVjBvVkt4RVlRQ1E0dkVMQWlTeW5WWWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["*"]
        apiGroups: ["", "rbac.authorization.k8s.io"]
        apiVersions: ["v1"]
        resources: ["pods", "roles", "clusterroles", "rolebindings", "clusterrolebindings"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]